### ISSUE TITLE
Starknet issue

### ISSUE THREAD

**Issue by ioogle** [MikeSpa/defi-project#1]
Hi Mike,

I'm Jeff, a Golang/Solidity developer from 1token.trade. I came across your project while researching Solidity proxy contracts and noticed that you're potentially eligible for an airdrop of 1000 STRK tokens. I thought I'd give you a heads-up in case you haven't claimed them yet. You can check and claim your tokens using your GitHub ID here: https://provisions.starknet.io/

Best,
Jeff

**Comment by MikeSpa** [comment]
Hi Jeff, thanks a lot for the tip!

**Comment by Armankhan566** [comment]
Good
